import * as R from "remeda";
import { materialDamageEffects } from "./damage.ts";
import { magicTraditions } from "./traits.ts";

const traditionIWR = R.mapValues(magicTraditions, (_, t) => `AVANT.Damage.IWR.Type.${t}`);

const materialIWR = R.mapValues(
    // Exclude niche materials from APs that have no IWR properties, as well as ones that count as more-common materials
    R.omit(materialDamageEffects, [
        "keep-stone",
        "peachwood",
        "sisterstone-dusk",
        "sisterstone-scarlet",
        "sovereign-steel",
        "warpglass",
    ]),
    (_v, k) => `AVANT.Damage.IWR.Type.${k}`,
);

const sanctifiedIWR = { holy: "AVANT.Damage.IWR.Type.holy", unholy: "AVANT.Damage.IWR.Type.unholy" };

const immunityTypes = {
    ...materialIWR,
    ...sanctifiedIWR,
    ...traditionIWR,
    acid: "AVANT.Damage.RollFlavor.acid",
    air: "AVANT.Damage.RollFlavor.air",
    alchemical: "AVANT.Damage.IWR.Type.alchemical",
    "area-damage": "AVANT.Damage.IWR.Type.area-damage",
    auditory: "AVANT.Damage.IWR.Type.auditory",
    bleed: "AVANT.Damage.RollFlavor.bleed",
    blinded: "AVANT.Damage.IWR.Type.blinded",
    bludgeoning: "AVANT.Damage.RollFlavor.bludgeoning",
    clumsy: "AVANT.Damage.IWR.Type.clumsy",
    cold: "AVANT.Damage.RollFlavor.cold",
    confused: "AVANT.Damage.IWR.Type.confused",
    controlled: "AVANT.Damage.IWR.Type.controlled",
    "critical-hits": "AVANT.Damage.IWR.Type.critical-hits",
    curse: "AVANT.Damage.IWR.Type.curse",
    custom: "", // Label provided by rule element
    dazzled: "AVANT.Damage.IWR.Type.dazzled",
    deafened: "AVANT.Damage.IWR.Type.deafened",
    "death-effects": "AVANT.Damage.IWR.Type.death-effects",
    detection: "AVANT.Damage.IWR.Type.detection",
    disease: "AVANT.Damage.IWR.Type.disease",
    doomed: "AVANT.Damage.IWR.Type.doomed",
    drained: "AVANT.Damage.IWR.Type.drained",
    earth: "AVANT.Damage.RollFlavor.earth",
    electricity: "AVANT.Damage.RollFlavor.electricity",
    emotion: "AVANT.Damage.IWR.Type.emotion",
    energy: "AVANT.Damage.IWR.Type.energy",
    enfeebled: "AVANT.Damage.IWR.Type.enfeebled",
    fascinated: "AVANT.Damage.IWR.Type.fascinated",
    fatigued: "AVANT.Damage.IWR.Type.fatigued",
    "fear-effects": "AVANT.Damage.IWR.Type.fear-effects",
    fire: "AVANT.Damage.RollFlavor.fire",
    fleeing: "AVANT.Damage.IWR.Type.fleeing",
    force: "AVANT.Damage.RollFlavor.force",
    "fortune-effects": "AVANT.Damage.IWR.Type.fortune-effects",
    frightened: "AVANT.Damage.IWR.Type.frightened",
    grabbed: "AVANT.Damage.IWR.Type.grabbed",
    healing: "AVANT.Damage.IWR.Type.healing",
    illusion: "AVANT.Damage.IWR.Type.illusion",
    immobilized: "AVANT.Damage.IWR.Type.immobilized",
    inhaled: "AVANT.Damage.IWR.Type.inhaled",
    light: "AVANT.Damage.IWR.Type.light",
    magic: "AVANT.Damage.IWR.Type.magic",
    mental: "AVANT.Damage.RollFlavor.mental",
    metal: "AVANT.Damage.IWR.Type.metal",
    "misfortune-effects": "AVANT.Damage.IWR.Type.misfortune-effects",
    "non-magical": "AVANT.Damage.IWR.Type.non-magical",
    "nonlethal-attacks": "AVANT.Damage.IWR.Type.nonlethal-attacks",
    "object-immunities": "AVANT.Damage.IWR.Type.object-immunities",
    "off-guard": "AVANT.Damage.IWR.Type.off-guard",
    olfactory: "AVANT.Damage.IWR.Type.olfactory",
    paralyzed: "AVANT.Damage.IWR.Type.paralyzed",
    "persistent-damage": "AVANT.Damage.IWR.Type.persistent-damage",
    petrified: "AVANT.Damage.IWR.Type.petrified",
    physical: "AVANT.Damage.IWR.Type.physical",
    piercing: "AVANT.Damage.RollFlavor.piercing",
    plant: "AVANT.Damage.IWR.Type.plant",
    poison: "AVANT.Damage.RollFlavor.poison",
    polymorph: "AVANT.Damage.IWR.Type.polymorph",
    possession: "AVANT.Damage.IWR.Type.possession",
    precision: "AVANT.Damage.RollFlavor.precision",
    prone: "AVANT.Damage.IWR.Type.prone",
    radiation: "AVANT.Damage.IWR.Type.radiation",
    restrained: "AVANT.Damage.IWR.Type.restrained",
    "salt-water": "AVANT.Damage.IWR.Type.salt-water",
    scrying: "AVANT.Damage.IWR.Type.scrying",
    sickened: "AVANT.Damage.IWR.Type.sickened",
    slashing: "AVANT.Damage.RollFlavor.slashing",
    sleep: "AVANT.Damage.IWR.Type.sleep",
    slowed: "AVANT.Damage.IWR.Type.slowed",
    sonic: "AVANT.Damage.RollFlavor.sonic",
    "spell-deflection": "AVANT.Damage.IWR.Type.spell-deflection",
    spirit: "AVANT.Damage.RollFlavor.spirit",
    stunned: "AVANT.Damage.IWR.Type.stunned",
    stupefied: "AVANT.Damage.IWR.Type.stupefied",
    "swarm-attacks": "AVANT.Damage.IWR.Type.swarm-attacks",
    "swarm-mind": "AVANT.Damage.IWR.Type.swarm-mind",
    trip: "AVANT.Damage.IWR.Type.trip",
    "unarmed-attacks": "AVANT.Damage.IWR.Type.unarmed-attacks",
    unconscious: "AVANT.Damage.IWR.Type.unconscious",
    visual: "AVANT.Damage.IWR.Type.visual",
    vitality: "AVANT.Damage.RollFlavor.vitality",
    void: "AVANT.Damage.RollFlavor.void",
    water: "AVANT.Damage.IWR.Type.water",
    wood: "AVANT.Damage.IWR.Type.wood",
    wounded: "AVANT.Damage.IWR.Type.wounded",
};

const weaknessTypes = {
    ...materialIWR,
    ...sanctifiedIWR,
    ...traditionIWR,
    acid: "AVANT.Damage.RollFlavor.acid",
    air: "AVANT.Damage.RollFlavor.air",
    alchemical: "AVANT.Damage.IWR.Type.alchemical",
    "all-damage": "AVANT.Damage.IWR.Type.all-damage",
    "area-damage": "AVANT.Damage.IWR.Type.area-damage",
    "arrow-vulnerability": "AVANT.Damage.IWR.Type.arrow-vulnerability",
    "axe-vulnerability": "AVANT.Damage.IWR.Type.axe-vulnerability",
    bleed: "AVANT.Damage.RollFlavor.bleed",
    bludgeoning: "AVANT.Damage.RollFlavor.bludgeoning",
    cold: "AVANT.Damage.RollFlavor.cold",
    "critical-hits": "AVANT.Damage.IWR.Type.critical-hits",
    custom: "", // Label provided by rule element
    earth: "AVANT.Damage.RollFlavor.earth",
    electricity: "AVANT.Damage.RollFlavor.electricity",
    emotion: "AVANT.Damage.IWR.Type.emotion",
    energy: "AVANT.Damage.IWR.Type.energy",
    fire: "AVANT.Damage.RollFlavor.fire",
    force: "AVANT.Damage.RollFlavor.force",
    "ghost-touch": "AVANT.Damage.IWR.Type.ghost-touch",
    glass: "AVANT.Damage.IWR.Type.glass",
    light: "AVANT.Damage.IWR.Type.light",
    magical: "AVANT.Damage.IWR.Type.magical",
    mental: "AVANT.Damage.RollFlavor.mental",
    metal: "AVANT.Damage.RollFlavor.metal",
    mythic: "AVANT.Damage.IWR.Type.mythic",
    "non-magical": "AVANT.Damage.IWR.Type.non-magical",
    "nonlethal-attacks": "AVANT.Damage.IWR.Type.nonlethal-attacks",
    "persistent-damage": "AVANT.Damage.IWR.Type.persistent-damage",
    physical: "AVANT.Damage.IWR.Type.physical",
    piercing: "AVANT.Damage.RollFlavor.piercing",
    plant: "AVANT.Damage.IWR.Type.plant",
    poison: "AVANT.Damage.RollFlavor.poison",
    precision: "AVANT.Damage.RollFlavor.precision",
    radiation: "AVANT.Damage.IWR.Type.radiation",
    salt: "AVANT.Damage.IWR.Type.salt",
    "salt-water": "AVANT.Damage.IWR.Type.salt-water",
    slashing: "AVANT.Damage.RollFlavor.slashing",
    sonic: "AVANT.Damage.RollFlavor.sonic",
    spells: "AVANT.Damage.IWR.Type.spells",
    spirit: "AVANT.Damage.RollFlavor.spirit",
    "splash-damage": "AVANT.Damage.IWR.Type.splash-damage",
    "unarmed-attacks": "AVANT.Damage.IWR.Type.unarmed-attacks",
    "vampire-weaknesses": "AVANT.Damage.IWR.Type.vampire-weaknesses",
    vitality: "AVANT.Damage.RollFlavor.vitality",
    void: "AVANT.Damage.RollFlavor.void",
    vorpal: "AVANT.Damage.IWR.Type.vorpal",
    "vorpal-fear": "AVANT.Damage.IWR.Type.vorpal-fear",
    "vulnerable-to-sunlight": "AVANT.Damage.IWR.Type.vulnerable-to-sunlight",
    water: "AVANT.Damage.IWR.Type.water",
    weapons: "AVANT.Damage.IWR.Type.weapons",
    "weapons-shedding-bright-light": "AVANT.Damage.IWR.Type.weapons-shedding-bright-light",
    wood: "AVANT.Damage.IWR.Type.wood",
};

const resistanceTypes = {
    ...materialIWR,
    ...sanctifiedIWR,
    ...traditionIWR,
    acid: "AVANT.Damage.RollFlavor.acid",
    air: "AVANT.Damage.RollFlavor.air",
    alchemical: "AVANT.Damage.IWR.Type.alchemical",
    "all-damage": "AVANT.Damage.IWR.Type.all-damage",
    "area-damage": "AVANT.Damage.IWR.Type.area-damage",
    axes: "AVANT.Damage.IWR.Type.axes",
    bleed: "AVANT.Damage.RollFlavor.bleed",
    bludgeoning: "AVANT.Damage.RollFlavor.bludgeoning",
    cold: "AVANT.Damage.RollFlavor.cold",
    "critical-hits": "AVANT.Damage.IWR.Type.critical-hits",
    custom: "", // Label provided by rule element
    "damage-from-spells": "AVANT.Damage.IWR.Type.damage-from-spells",
    earth: "AVANT.Damage.RollFlavor.earth",
    electricity: "AVANT.Damage.RollFlavor.electricity",
    energy: "AVANT.Damage.IWR.Type.energy",
    fire: "AVANT.Damage.RollFlavor.fire",
    force: "AVANT.Damage.RollFlavor.force",
    "ghost-touch": "AVANT.Damage.IWR.Type.ghost-touch",
    light: "AVANT.Damage.IWR.Type.light",
    magical: "AVANT.Damage.IWR.Type.magical",
    mental: "AVANT.Damage.RollFlavor.mental",
    metal: "AVANT.Damage.RollFlavor.metal",
    mythic: "AVANT.Damage.IWR.Type.mythic",
    "non-magical": "AVANT.Damage.IWR.Type.non-magical",
    nonlethal: "AVANT.Damage.IWR.Type.nonlethal",
    "nonlethal-attacks": "AVANT.Damage.IWR.Type.nonlethal-attacks",
    "persistent-damage": "AVANT.Damage.IWR.Type.persistent-damage",
    physical: "AVANT.Damage.IWR.Type.physical",
    piercing: "AVANT.Damage.RollFlavor.piercing",
    plant: "AVANT.Damage.IWR.Type.plant",
    poison: "AVANT.Damage.RollFlavor.poison",
    precision: "AVANT.Damage.RollFlavor.precision",
    "protean-anatomy": "AVANT.Damage.IWR.Type.protean-anatomy",
    radiation: "AVANT.Damage.IWR.Type.radiation",
    salt: "AVANT.Damage.IWR.Type.salt",
    "salt-water": "AVANT.Damage.IWR.Type.salt-water",
    slashing: "AVANT.Damage.RollFlavor.slashing",
    sonic: "AVANT.Damage.RollFlavor.sonic",
    spells: "AVANT.Damage.IWR.Type.spells",
    spirit: "AVANT.Damage.RollFlavor.spirit",
    "unarmed-attacks": "AVANT.Damage.IWR.Type.unarmed-attacks",
    vitality: "AVANT.Damage.RollFlavor.vitality",
    void: "AVANT.Damage.RollFlavor.void",
    vorpal: "AVANT.Damage.IWR.Type.vorpal",
    "vorpal-adamantine": "AVANT.Damage.IWR.Type.vorpal-adamantine",
    water: "AVANT.Damage.IWR.Type.water",
    weapons: "AVANT.Damage.IWR.Type.weapons",
    "weapons-shedding-bright-light": "AVANT.Damage.IWR.Type.weapons-shedding-bright-light",
    wood: "AVANT.Damage.IWR.Type.wood",
};

export { immunityTypes, resistanceTypes, weaknessTypes };
