import { OtherArmorTag } from "@item/armor/types.ts";
import { BackgroundTrait } from "@item/background/types.ts";
import { RANGE_TRAITS } from "@item/base/data/values.ts";
import { ClassTrait } from "@item/class/types.ts";
import { OtherConsumableTag } from "@item/consumable/types.ts";
import { PreciousMaterialType } from "@item/physical/types.ts";
import { MagicTradition } from "@item/spell/types.ts";
import { OtherWeaponTag } from "@item/weapon/types.ts";
import { sluggify } from "@util";
import * as R from "remeda";

// Ancestry and heritage traits
const ancestryTraits = {
    aiuvarin: "AVANT.TraitAiuvarin",
    anadi: "AVANT.TraitAnadi",
    android: "AVANT.TraitAndroid",
    aphorite: "AVANT.TraitAphorite",
    ardande: "AVANT.TraitArdande",
    athamaru: "AVANT.TraitAthamaru",
    automaton: "AVANT.TraitAutomaton",
    "awakened-animal": "AVANT.TraitAwakenedAnimal",
    azarketi: "AVANT.TraitAzarketi",
    beastkin: "AVANT.TraitBeastkin",
    bugbear: "AVANT.TraitBugbear",
    catfolk: "AVANT.TraitCatfolk",
    centaur: "AVANT.TraitCentaur",
    changeling: "AVANT.TraitChangeling",
    conrasu: "AVANT.TraitConrasu",
    dhampir: "AVANT.TraitDhampir",
    dragonblood: "AVANT.TraitDragonblood",
    dromaar: "AVANT.TraitDromaar",
    duskwalker: "AVANT.TraitDuskwalker",
    dwarf: "AVANT.TraitDwarf",
    elf: "AVANT.TraitElf",
    fetchling: "AVANT.TraitFetchling",
    fleshwarp: "AVANT.TraitFleshwarp",
    ganzi: "AVANT.TraitGanzi",
    geniekin: "AVANT.TraitGeniekin",
    ghoran: "AVANT.TraitGhoran",
    gnoll: "AVANT.TraitGnoll",
    gnome: "AVANT.TraitGnome",
    goblin: "AVANT.TraitGoblin",
    goloma: "AVANT.TraitGoloma",
    grippli: "AVANT.TraitGrippli",
    halfling: "AVANT.TraitHalfling",
    hobgoblin: "AVANT.TraitHobgoblin",
    human: "AVANT.TraitHuman",
    hungerseed: "AVANT.TraitHungerseed",
    kashrishi: "AVANT.TraitKashrishi",
    kitsune: "AVANT.TraitKitsune",
    kobold: "AVANT.TraitKobold",
    leshy: "AVANT.TraitLeshy",
    lizardfolk: "AVANT.TraitLizardfolk",
    merfolk: "AVANT.TraitMerfolk",
    minotaur: "AVANT.TraitMinotaur",
    nagaji: "AVANT.TraitNagaji",
    naari: "AVANT.TraitNaari",
    nephilim: "AVANT.TraitNephilim",
    orc: "AVANT.TraitOrc",
    oread: "AVANT.TraitOread",
    poppet: "AVANT.TraitPoppet",
    ratfolk: "AVANT.TraitRatfolk",
    reflection: "AVANT.TraitReflection",
    samsaran: "AVANT.TraitSamsaran",
    sarangay: "AVANT.TraitSarangay",
    shisk: "AVANT.TraitShisk",
    shoony: "AVANT.TraitShoony",
    skeleton: "AVANT.TraitSkeleton",
    sprite: "AVANT.TraitSprite",
    strix: "AVANT.TraitStrix",
    suli: "AVANT.TraitSuli",
    surki: "AVANT.TraitSurki",
    sylph: "AVANT.TraitSylph",
    tanuki: "AVANT.TraitTanuki",
    talos: "AVANT.TraitTalos",
    tengu: "AVANT.TraitTengu",
    undine: "AVANT.TraitUndine",
    vanara: "AVANT.TraitVanara",
    vishkanya: "AVANT.TraitVishkanya",
    wayang: "AVANT.TraitWayang",
    yaksha: "AVANT.TraitYaksha",
    yaoguai: "AVANT.TraitYaoguai",
};

const elementTraits = {
    air: "AVANT.TraitAir",
    earth: "AVANT.TraitEarth",
    fire: "AVANT.TraitFire",
    metal: "AVANT.TraitMetal",
    water: "AVANT.TraitWater",
    wood: "AVANT.TraitWood",
};
type ElementTrait = keyof typeof elementTraits;

const energyDamageTypes = {
    acid: "AVANT.TraitAcid",
    cold: "AVANT.TraitCold",
    electricity: "AVANT.TraitElectricity",
    fire: "AVANT.TraitFire",
    force: "AVANT.TraitForce",
    sonic: "AVANT.TraitSonic",
    vitality: "AVANT.TraitVitality",
    void: "AVANT.TraitVoid",
};

const magicTraditions: Record<MagicTradition, string> = {
    arcane: "AVANT.TraitArcane",
    divine: "AVANT.TraitDivine",
    occult: "AVANT.TraitOccult",
    primal: "AVANT.TraitPrimal",
};

const sanctificationTraits = {
    holy: "AVANT.TraitHoly",
    unholy: "AVANT.TraitUnholy",
};

const creatureTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    aberration: "AVANT.TraitAberration",
    aeon: "AVANT.TraitAeon",
    aesir: "AVANT.TraitAesir",
    agathion: "AVANT.TraitAgathion",
    alchemical: "AVANT.TraitAlchemical",
    amphibious: "AVANT.TraitAmphibious",
    angel: "AVANT.TraitAngel",
    animal: "AVANT.TraitAnimal",
    anugobu: "AVANT.TraitAnugobu",
    aquatic: "AVANT.TraitAquatic",
    archon: "AVANT.TraitArchon",
    astral: "AVANT.TraitAstral",
    asura: "AVANT.TraitAsura",
    azata: "AVANT.TraitAzata",
    beast: "AVANT.TraitBeast",
    blight: "AVANT.TraitBlight",
    boggard: "AVANT.TraitBoggard",
    bugbear: "AVANT.TraitBugbear",
    caligni: "AVANT.TraitCaligni",
    celestial: "AVANT.TraitCelestial",
    centaur: "AVANT.TraitCentaur",
    "charau-ka": "AVANT.TraitCharauKa",
    clockwork: "AVANT.TraitClockwork",
    construct: "AVANT.TraitConstruct",
    couatl: "AVANT.TraitCouatl",
    daemon: "AVANT.TraitDaemon",
    darvakka: "AVANT.TraitDarvakka",
    demon: "AVANT.TraitDemon",
    dero: "AVANT.TraitDero",
    devil: "AVANT.TraitDevil",
    dinosaur: "AVANT.TraitDinosaur",
    div: "AVANT.TraitDiv",
    dragon: "AVANT.TraitDragon",
    dream: "AVANT.TraitDream",
    drow: "AVANT.TraitDrow",
    duergar: "AVANT.TraitDuergar",
    eidolon: "AVANT.TraitEidolon",
    elemental: "AVANT.TraitElemental",
    ethereal: "AVANT.TraitEthereal",
    experiment: "AVANT.TraitExperiment",
    fey: "AVANT.TraitFey",
    fiend: "AVANT.TraitFiend",
    formian: "AVANT.TraitFormian",
    fungus: "AVANT.TraitFungus",
    genie: "AVANT.TraitGenie",
    ghoran: "AVANT.TraitGhoran",
    ghost: "AVANT.TraitGhost",
    ghoul: "AVANT.TraitGhoul",
    ghul: "AVANT.TraitGhul",
    giant: "AVANT.TraitGiant",
    golem: "AVANT.TraitGolem",
    graveknight: "AVANT.TraitGraveknight",
    gremlin: "AVANT.TraitGremlin",
    grioth: "AVANT.TraitGrioth",
    hag: "AVANT.TraitHag",
    hantu: "AVANT.TraitHantu",
    herald: "AVANT.TraitHerald",
    hryngar: "AVANT.TraitHryngar",
    humanoid: "AVANT.TraitHumanoid",
    ikeshti: "AVANT.TraitIkeshti",
    illusion: "AVANT.TraitIllusion",
    incorporeal: "AVANT.TraitIncorporeal",
    inevitable: "AVANT.TraitInevitable",
    kami: "AVANT.TraitKami",
    kaiju: "AVANT.TraitKaiju",
    kovintus: "AVANT.TraitKovintus",
    light: "AVANT.TraitLight",
    lilu: "AVANT.TraitLilu",
    locathah: "AVANT.TraitLocathah",
    mental: "AVANT.TraitMental",
    merfolk: "AVANT.TraitMerfolk",
    mindless: "AVANT.TraitMindless",
    minion: "AVANT.TraitMinion",
    monitor: "AVANT.TraitMonitor",
    morlock: "AVANT.TraitMorlock",
    mortic: "AVANT.TraitMortic",
    mummy: "AVANT.TraitMummy",
    munavri: "AVANT.TraitMunavri",
    mutant: "AVANT.TraitMutant",
    mythic: "AVANT.TraitMythic",
    nindoru: "AVANT.TraitNindoru",
    nymph: "AVANT.TraitNymph",
    oni: "AVANT.TraitOni",
    ooze: "AVANT.TraitOoze",
    oread: "AVANT.TraitOread",
    paaridar: "AVANT.TraitPaaridar",
    palinthanos: "AVANT.TraitPalinthanos",
    "persona-flirt": "AVANT.TraitPersonaFlirt",
    "persona-guardian": "AVANT.TraitPersonaGuardian",
    "persona-leader": "AVANT.TraitPersonaLeader",
    "persona-scholar": "AVANT.TraitPersonaScholar",
    "persona-scoundrel": "AVANT.TraitPersonaScoundrel",
    "persona-underdog": "AVANT.TraitPersonaUnderdog",
    "persona-warrior": "AVANT.TraitPersonaWarrior",
    "persona-wildcard": "AVANT.TraitPersonaWildcard",
    petitioner: "AVANT.TraitPetitioner",
    phantom: "AVANT.TraitPhantom",
    plant: "AVANT.TraitPlant",
    poison: "AVANT.TraitPoison",
    protean: "AVANT.TraitProtean",
    psychopomp: "AVANT.TraitPsychopomp",
    qlippoth: "AVANT.TraitQlippoth",
    rakshasa: "AVANT.TraitRakshasa",
    reflection: "AVANT.TraitReflection",
    sahkil: "AVANT.TraitSahkil",
    "sea-devil": "AVANT.TraitSeaDevil",
    sedacthy: "AVANT.TraitSedacthy",
    serpentfolk: "AVANT.TraitSerpentfolk",
    seugathi: "AVANT.TraitSeugathi",
    shabti: "AVANT.TraitShabti",
    shade: "AVANT.TraitShade",
    shadow: "AVANT.TraitShadow",
    shobhad: "AVANT.TraitShobhad",
    siktempora: "AVANT.TraitSiktempora",
    skelm: "AVANT.TraitSkelm",
    skulk: "AVANT.TraitSkulk",
    soulbound: "AVANT.TraitSoulbound",
    spirit: "AVANT.TraitSpirit",
    sporeborn: "AVANT.TraitSporeborn",
    spriggan: "AVANT.TraitSpriggan",
    stheno: "AVANT.TraitStheno",
    summoned: "AVANT.TraitSummoned",
    swarm: "AVANT.TraitSwarm",
    tane: "AVANT.TraitTane",
    tanggal: "AVANT.TraitTanggal",
    time: "AVANT.TraitTime",
    titan: "AVANT.TraitTitan",
    troll: "AVANT.TraitTroll",
    troop: "AVANT.TraitTroop",
    undead: "AVANT.TraitUndead",
    urdefhan: "AVANT.TraitUrdefhan",
    vampire: "AVANT.TraitVampire",
    vanara: "AVANT.TraitVanara",
    velstrac: "AVANT.TraitVelstrac",
    wayang: "AVANT.TraitWayang",
    werecreature: "AVANT.TraitWerecreature",
    wight: "AVANT.TraitWight",
    "wild-hunt": "AVANT.TraitWildHunt",
    wraith: "AVANT.TraitWraith",
    wraithvine: "AVANT.TraitWraithvine",
    wyrwood: "AVANT.TraitWyrwood",
    xulgath: "AVANT.TraitXulgath",
    zombie: "AVANT.TraitZombie",
};

const backgroundTraits: Record<BackgroundTrait, string> = {
    "persona-flirt": "AVANT.TraitPersonaFlirt",
    "persona-guardian": "AVANT.TraitPersonaGuardian",
    "persona-leader": "AVANT.TraitPersonaLeader",
    "persona-scholar": "AVANT.TraitPersonaScholar",
    "persona-scoundrel": "AVANT.TraitPersonaScoundrel",
    "persona-underdog": "AVANT.TraitPersonaUnderdog",
    "persona-warrior": "AVANT.TraitPersonaWarrior",
    "persona-wildcard": "AVANT.TraitPersonaWildcard",
    "pervasive-magic": "AVANT.TraitPervasiveMagic",
};

const classTraits: Record<ClassTrait, string> = {
    alchemist: "AVANT.TraitAlchemist",
    animist: "AVANT.TraitAnimist",
    barbarian: "AVANT.TraitBarbarian",
    bard: "AVANT.TraitBard",
    champion: "AVANT.TraitChampion",
    cleric: "AVANT.TraitCleric",
    druid: "AVANT.TraitDruid",
    exemplar: "AVANT.TraitExemplar",
    fighter: "AVANT.TraitFighter",
    gunslinger: "AVANT.TraitGunslinger",
    inventor: "AVANT.TraitInventor",
    investigator: "AVANT.TraitInvestigator",
    kineticist: "AVANT.TraitKineticist",
    magus: "AVANT.TraitMagus",
    monk: "AVANT.TraitMonk",
    oracle: "AVANT.TraitOracle",
    psychic: "AVANT.TraitPsychic",
    ranger: "AVANT.TraitRanger",
    rogue: "AVANT.TraitRogue",
    sorcerer: "AVANT.TraitSorcerer",
    summoner: "AVANT.TraitSummoner",
    swashbuckler: "AVANT.TraitSwashbuckler",
    thaumaturge: "AVANT.TraitThaumaturge",
    witch: "AVANT.TraitWitch",
    wizard: "AVANT.TraitWizard",
};

const damageTraits = {
    ...elementTraits,
    ...energyDamageTypes,
    ...sanctificationTraits,
    light: "AVANT.TraitLight",
    magical: "AVANT.TraitMagical",
    mental: "AVANT.TraitMental",
    nonlethal: "AVANT.TraitNonlethal",
    plant: "AVANT.TraitPlant",
    radiation: "AVANT.TraitRadiation",
    spirit: "AVANT.TraitSpirit",
    vitality: "AVANT.TraitVitality",
    void: "AVANT.TraitVoid",
};

const spellTraits = {
    ...classTraits,
    ...damageTraits,
    ...elementTraits,
    ...magicTraditions,
    ...sanctificationTraits,
    amp: "AVANT.TraitAmp",
    attack: "AVANT.TraitAttack",
    auditory: "AVANT.TraitAuditory",
    aura: "AVANT.TraitAura",
    beast: "AVANT.TraitBeast",
    cantrip: "AVANT.TraitCantrip",
    composition: "AVANT.TraitComposition",
    concentrate: "AVANT.TraitConcentrate",
    consecration: "AVANT.TraitConsecration",
    contingency: "AVANT.TraitContingency",
    curse: "AVANT.TraitCurse",
    cursebound: "AVANT.TraitCursebound",
    darkness: "AVANT.TraitDarkness",
    death: "AVANT.TraitDeath",
    detection: "AVANT.TraitDetection",
    disease: "AVANT.TraitDisease",
    dream: "AVANT.TraitDream",
    eidolon: "AVANT.TraitEidolon",
    emotion: "AVANT.TraitEmotion",
    exploration: "AVANT.TraitExploration",
    extradimensional: "AVANT.TraitExtradimensional",
    fear: "AVANT.TraitFear",
    focus: "AVANT.TraitFocus",
    fortune: "AVANT.TraitFortune",
    fungus: "AVANT.TraitFungus",
    healing: "AVANT.TraitHealing",
    hex: "AVANT.TraitHex",
    illusion: "AVANT.TraitIllusion",
    incapacitation: "AVANT.TraitIncapacitation",
    incarnate: "AVANT.TraitIncarnate",
    incorporeal: "AVANT.TraitIncorporeal",
    inhaled: "AVANT.TraitInhaled",
    light: "AVANT.TraitLight",
    linguistic: "AVANT.TraitLinguistic",
    litany: "AVANT.TraitLitany",
    manipulate: "AVANT.TraitManipulate",
    misfortune: "AVANT.TraitMisfortune",
    morph: "AVANT.TraitMorph",
    move: "AVANT.TraitMove",
    mythic: "AVANT.TraitMythic",
    nonlethal: "AVANT.TraitNonlethal",
    olfactory: "AVANT.TraitOlfactory",
    plant: "AVANT.TraitPlant",
    poison: "AVANT.TraitPoison",
    polymorph: "AVANT.TraitPolymorph",
    possession: "AVANT.TraitPossession",
    prediction: "AVANT.TraitPrediction",
    psyche: "AVANT.TraitPsyche",
    rage: "AVANT.TraitRage",
    revelation: "AVANT.TraitRevelation",
    sanctified: "AVANT.TraitSanctified",
    scrying: "AVANT.TraitScrying",
    shadow: "AVANT.TraitShadow",
    sleep: "AVANT.TraitSleep",
    spellshape: "AVANT.TraitSpellshape",
    stance: "AVANT.TraitStance",
    structure: "AVANT.TraitStructure",
    subtle: "AVANT.TraitSubtle",
    summon: "AVANT.TraitSummon",
    summoned: "AVANT.TraitSummoned",
    teleportation: "AVANT.TraitTeleportation",
    trial: "AVANT.TraitTrial",
    "true-name": "AVANT.TraitTrueName",
    visual: "AVANT.TraitVisual",
};

const weaponTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    adjusted: "AVANT.TraitAdjusted",
    alchemical: "AVANT.TraitAlchemical",
    agile: "AVANT.TraitAgile",
    apex: "AVANT.TraitApex",
    artifact: "AVANT.TraitArtifact",
    attached: "AVANT.TraitAttached",
    "attached-to-shield": "AVANT.TraitAttachedToShield",
    "attached-to-crossbow-or-firearm": "AVANT.TraitAttachedToCrossbowOrFirearm",
    auditory: "AVANT.TraitAuditory",
    backstabber: "AVANT.TraitBackstabber",
    backswing: "AVANT.TraitBackswing",
    bomb: "AVANT.TraitBomb",
    brace: "AVANT.TraitBrace",
    brutal: "AVANT.TraitBrutal",
    "capacity-2": "AVANT.TraitCapacity2",
    "capacity-3": "AVANT.TraitCapacity3",
    "capacity-4": "AVANT.TraitCapacity4",
    "capacity-5": "AVANT.TraitCapacity5",
    climbing: "AVANT.TraitClimbing",
    clockwork: "AVANT.TraitClockwork",
    cobbled: "AVANT.TraitCobbled",
    combination: "AVANT.TraitCombination",
    concealable: "AVANT.TraitConcealable",
    concussive: "AVANT.TraitConcussive",
    consumable: "AVANT.TraitConsumable",
    "critical-fusion": "AVANT.TraitCriticalFusion",
    cursed: "AVANT.TraitCursed",
    "deadly-d4": "AVANT.TraitDeadlyD4",
    "deadly-d6": "AVANT.TraitDeadlyD6",
    "deadly-d8": "AVANT.TraitDeadlyD8",
    "deadly-d10": "AVANT.TraitDeadlyD10",
    "deadly-d12": "AVANT.TraitDeadlyD12",
    death: "AVANT.TraitDeath",
    disarm: "AVANT.TraitDisarm",
    disease: "AVANT.TraitDisease",
    "double-barrel": "AVANT.TraitDoubleBarrel",
    emotion: "AVANT.TraitEmotion",
    extradimensional: "AVANT.TraitExtradimensional",
    "fatal-aim-d10": "AVANT.TraitFatalAimD10",
    "fatal-aim-d12": "AVANT.TraitFatalAimD12",
    "fatal-d8": "AVANT.TraitFatalD8",
    "fatal-d10": "AVANT.TraitFatalD10",
    "fatal-d12": "AVANT.TraitFatalD12",
    fear: "AVANT.TraitFear",
    finesse: "AVANT.TraitFinesse",
    forceful: "AVANT.TraitForceful",
    fortune: "AVANT.TraitFortune",
    "free-hand": "AVANT.TraitFreeHand",
    fungus: "AVANT.TraitFungus",
    grapple: "AVANT.TraitGrapple",
    hampering: "AVANT.TraitHampering",
    healing: "AVANT.TraitHealing",
    illusion: "AVANT.TraitIllusion",
    infused: "AVANT.TraitInfused",
    inhaled: "AVANT.TraitInhaled",
    injection: "AVANT.TraitInjection",
    intelligent: "AVANT.TraitIntelligent",
    invested: "AVANT.TraitInvested",
    "jousting-d4": "AVANT.TraitJoustingD4",
    "jousting-d6": "AVANT.TraitJoustingD6",
    "jousting-d8": "AVANT.TraitJoustingD8",
    "jousting-d10": "AVANT.TraitJoustingD10",
    kickback: "AVANT.TraitKickback",
    light: "AVANT.TraitLight",
    magical: "AVANT.TraitMagical",
    mental: "AVANT.TraitMental",
    modular: "AVANT.TraitModular",
    monk: "AVANT.TraitMonk",
    mythic: "AVANT.TraitMythic",
    nonlethal: "AVANT.TraitNonlethal",
    olfactory: "AVANT.TraitOlfactory",
    parry: "AVANT.TraitParry",
    plant: "AVANT.TraitPlant",
    poison: "AVANT.TraitPoison",
    propulsive: "AVANT.TraitPropulsive",
    "ranged-trip": "AVANT.TraitRangedTrip",
    razing: "AVANT.TraitRazing",
    reach: "AVANT.TraitReach",
    recovery: "AVANT.TraitRecovery",
    relic: "AVANT.TraitRelic",
    repeating: "AVANT.TraitRepeating",
    resonant: "AVANT.TraitResonant",
    saggorak: "AVANT.TraitSaggorak",
    "scatter-5": "AVANT.TraitScatter5",
    "scatter-10": "AVANT.TraitScatter10",
    "scatter-15": "AVANT.TraitScatter15",
    "scatter-20": "AVANT.TraitScatter20",
    scrying: "AVANT.TraitScrying",
    shadow: "AVANT.TraitShadow",
    shove: "AVANT.TraitShove",
    spirit: "AVANT.TraitSpirit",
    splash: "AVANT.TraitSplash",
    staff: "AVANT.TraitStaff",
    sweep: "AVANT.TraitSweep",
    tearing: "AVANT.TraitTearing",
    tech: "AVANT.TraitTech",
    teleportation: "AVANT.TraitTeleportation",
    tethered: "AVANT.TraitTethered",
    thrown: "AVANT.TraitThrown",
    "thrown-10": "AVANT.TraitThrown10",
    "thrown-15": "AVANT.TraitThrown15",
    "thrown-20": "AVANT.TraitThrown20",
    "thrown-30": "AVANT.TraitThrown30",
    "thrown-40": "AVANT.TraitThrown40",
    "thrown-50": "AVANT.TraitThrown50",
    "thrown-60": "AVANT.TraitThrown60",
    "thrown-80": "AVANT.TraitThrown80",
    "thrown-100": "AVANT.TraitThrown100",
    "thrown-200": "AVANT.TraitThrown200",
    training: "AVANT.TraitTraining",
    trip: "AVANT.TraitTrip",
    twin: "AVANT.TraitTwin",
    "two-hand-d6": "AVANT.TraitTwoHandD6",
    "two-hand-d8": "AVANT.TraitTwoHandD8",
    "two-hand-d10": "AVANT.TraitTwoHandD10",
    "two-hand-d12": "AVANT.TraitTwoHandD12",
    unarmed: "AVANT.TraitUnarmed",
    vehicular: "AVANT.TraitVehicular",
    venomous: "AVANT.TraitVenomous",
    "versatile-acid": "AVANT.TraitVersatileAcid",
    "versatile-b": "AVANT.TraitVersatileB",
    "versatile-cold": "AVANT.TraitVersatileCold",
    "versatile-electricity": "AVANT.TraitVersatileElectricity",
    "versatile-fire": "AVANT.TraitVersatileFire",
    "versatile-force": "AVANT.TraitVersatileForce",
    "versatile-mental": "AVANT.TraitVersatileMental",
    "versatile-p": "AVANT.TraitVersatileP",
    "versatile-poison": "AVANT.TraitVersatilePoison",
    "versatile-s": "AVANT.TraitVersatileS",
    "versatile-sonic": "AVANT.TraitVersatileSonic",
    "versatile-spirit": "AVANT.TraitVersatileSpirit",
    "versatile-vitality": "AVANT.TraitVersatileVitality",
    "versatile-void": "AVANT.TraitVersatileVoid",
    "volley-20": "AVANT.TraitVolley20",
    "volley-30": "AVANT.TraitVolley30",
    "volley-50": "AVANT.TraitVolley50",
    "volley-60": "AVANT.TraitVolley60",
    wand: "AVANT.TraitWand",
};

const preciousMaterials: Record<PreciousMaterialType, string> = {
    abysium: "AVANT.PreciousMaterialAbysium",
    adamantine: "AVANT.PreciousMaterialAdamantine",
    "cold-iron": "AVANT.PreciousMaterialColdIron",
    dawnsilver: "AVANT.PreciousMaterialDawnsilver",
    duskwood: "AVANT.PreciousMaterialDuskwood",
    djezet: "AVANT.PreciousMaterialDjezet",
    dragonhide: "AVANT.PreciousMaterialDragonhide",
    dreamweb: "AVANT.PreciousMaterialDreamweb",
    "grisantian-pelt": "AVANT.PreciousMaterialGrisantianPelt",
    inubrix: "AVANT.PreciousMaterialInubrix",
    "keep-stone": "AVANT.PreciousMaterialKeepStone",
    noqual: "AVANT.PreciousMaterialNoqual",
    orichalcum: "AVANT.PreciousMaterialOrichalcum",
    peachwood: "AVANT.PreciousMaterialPeachwood",
    siccatite: "AVANT.PreciousMaterialSiccatite",
    silver: "AVANT.PreciousMaterialSilver",
    sisterstone: "AVANT.PreciousMaterialSisterstone",
    "sisterstone-dusk": "AVANT.PreciousMaterialSisterstoneDusk",
    "sisterstone-scarlet": "AVANT.PreciousMaterialSisterstoneScarlet",
    sloughstone: "AVANT.PreciousMaterialSloughstone",
    "sovereign-steel": "AVANT.PreciousMaterialSovereignSteel",
    warpglass: "AVANT.PreciousMaterialWarpglass",
};

const otherArmorTags: Record<OtherArmorTag, string> = {
    shoddy: "AVANT.Item.Physical.OtherTag.Shoddy",
};

const otherConsumableTags: Record<OtherConsumableTag, string> = {
    "alchemical-food": "AVANT.Item.Physical.OtherTag.AlchemicalFood",
    "alchemical-tool": "AVANT.Item.Physical.OtherTag.AlchemicalTool",
    herbal: "AVANT.Item.Physical.OtherTag.Herbal",
};

const otherWeaponTags: Record<OtherWeaponTag, string> = {
    "handwraps-of-mighty-blows": "AVANT.Item.Physical.OtherTag.HandwrapsOfMightyBlows",
    improvised: "AVANT.Item.Physical.OtherTag.Improvised",
    shoddy: "AVANT.Item.Physical.OtherTag.Shoddy",
};

const rangeTraits = R.mapToObj(RANGE_TRAITS, (trait) => [trait, `AVANT.Trait${sluggify(trait, { camel: "bactrian" })}`]);

const npcAttackTraits = {
    ...weaponTraits,
    ...preciousMaterials,
    ...rangeTraits,
    concentrate: "AVANT.TraitConcentrate",
    curse: "AVANT.TraitCurse",
    "deadly-2d8": "AVANT.TraitDeadly2D8",
    "deadly-3d8": "AVANT.TraitDeadly3D8",
    "deadly-4d8": "AVANT.TraitDeadly4D8",
    "deadly-2d10": "AVANT.TraitDeadly2D10",
    "deadly-3d10": "AVANT.TraitDeadly3D10",
    "deadly-4d10": "AVANT.TraitDeadly4D10",
    "deadly-2d12": "AVANT.TraitDeadly2D12",
    "deadly-3d12": "AVANT.TraitDeadly3D12",
    "deadly-4d12": "AVANT.TraitDeadly4D12",
    illusion: "AVANT.TraitIllusion",
    impulse: "AVANT.TraitImpulse",
    incorporeal: "AVANT.TraitIncorporeal",
    radiation: "AVANT.TraitRadiation",
    "reach-0": "AVANT.TraitReach0",
    "reach-10": "AVANT.TraitReach10",
    "reach-15": "AVANT.TraitReach15",
    "reach-20": "AVANT.TraitReach20",
    "reach-25": "AVANT.TraitReach25",
    "reach-30": "AVANT.TraitReach30",
    "reach-40": "AVANT.TraitReach40",
    "reach-50": "AVANT.TraitReach50",
    "reach-60": "AVANT.TraitReach60",
    "reach-100": "AVANT.TraitReach100",
    "reach-120": "AVANT.TraitReach120",
    "reach-200": "AVANT.TraitReach200",
    "reach-1000": "AVANT.TraitReach1000",
    "reload-0": "AVANT.TraitReload0",
    "reload-1": "AVANT.TraitReload1",
    "reload-2": "AVANT.TraitReload2",
    "reload-1-min": "AVANT.TraitReload1Min",
    sanctified: "AVANT.TraitSanctified",
};

const featTraits = {
    ...ancestryTraits,
    ...classTraits,
    ...damageTraits,
    ...magicTraditions,
    ...spellTraits,
    additive: "AVANT.TraitAdditive",
    additive1: "AVANT.TraitAdditive1",
    additive2: "AVANT.TraitAdditive2",
    additive3: "AVANT.TraitAdditive3",
    aftermath: "AVANT.TraitAftermath",
    alchemical: "AVANT.TraitAlchemical",
    apparition: "AVANT.TraitApparition",
    archetype: "AVANT.TraitArchetype",
    artifact: "AVANT.TraitArtifact",
    auditory: "AVANT.TraitAuditory",
    aura: "AVANT.TraitAura",
    bravado: "AVANT.TraitBravado",
    calling: "AVANT.TraitCalling",
    circus: "AVANT.TraitCircus",
    class: "TYPES.Item.class",
    coagulant: "AVANT.TraitCoagulant",
    composite: "AVANT.TraitComposite",
    concentrate: "AVANT.TraitConcentrate",
    dedication: "AVANT.TraitDedication",
    destiny: "AVANT.TraitDestiny",
    detection: "AVANT.TraitDetection",
    deviant: "AVANT.TraitDeviant",
    downtime: "AVANT.TraitDowntime",
    emotion: "AVANT.TraitEmotion",
    evolution: "AVANT.TraitEvolution",
    esoterica: "AVANT.TraitEsoterica",
    exploration: "AVANT.TraitExploration",
    fear: "AVANT.TraitFear",
    finisher: "AVANT.TraitFinisher",
    flourish: "AVANT.TraitFlourish",
    fortune: "AVANT.TraitFortune",
    general: "AVANT.TraitGeneral",
    ikon: "AVANT.TraitIkon",
    impulse: "AVANT.TraitImpulse",
    infusion: "AVANT.TraitInfusion",
    injury: "AVANT.TraitInjury",
    lineage: "AVANT.TraitLineage",
    manipulate: "AVANT.TraitManipulate",
    mindshift: "AVANT.TraitMindshift",
    modification: "AVANT.TraitModification",
    move: "AVANT.TraitMove",
    multiclass: "AVANT.TraitMulticlass",
    oath: "AVANT.TraitOath",
    olfactory: "AVANT.TraitOlfactory",
    overflow: "AVANT.TraitOverflow",
    "pervasive-magic": "AVANT.TraitPervasiveMagic",
    poison: "AVANT.TraitPoison",
    press: "AVANT.TraitPress",
    rage: "AVANT.TraitRage",
    reckless: "AVANT.TraitReckless",
    reincarnated: "AVANT.TraitReincarnated",
    reflection: "AVANT.TraitReflection",
    secret: "AVANT.TraitSecret",
    skill: "AVANT.TraitSkill",
    social: "AVANT.TraitSocial",
    spellshot: "AVANT.TraitSpellshot",
    stamina: "AVANT.TraitStamina",
    stance: "AVANT.TraitStance",
    talisman: "AVANT.TraitTalisman",
    tandem: "AVANT.TraitTandem",
    time: "AVANT.TraitTime",
    transcendence: "AVANT.TraitTranscendence",
    "true-name": "AVANT.TraitTrueName",
    unstable: "AVANT.TraitUnstable",
    vigilante: "AVANT.TraitVigilante",
    virulent: "AVANT.TraitVirulent",
    vitality: "AVANT.TraitVitality",
    void: "AVANT.TraitVoid",
    wandering: "AVANT.TraitWandering",
};

const consumableTraits = {
    ...spellTraits,
    additive: "AVANT.TraitAdditive",
    additive1: "AVANT.TraitAdditive1",
    additive2: "AVANT.TraitAdditive2",
    additive3: "AVANT.TraitAdditive3",
    alchemical: "AVANT.TraitAlchemical",
    attack: "AVANT.TraitAttack",
    auditory: "AVANT.TraitAuditory",
    aura: "AVANT.TraitAura",
    "bottled-breath": "AVANT.TraitBottledBreath",
    catalyst: "AVANT.TraitCatalyst",
    coagulant: "AVANT.TraitCoagulant",
    clockwork: "AVANT.TraitClockwork",
    consumable: "AVANT.TraitConsumable",
    contact: "AVANT.TraitContact",
    curse: "AVANT.TraitCurse",
    cursed: "AVANT.TraitCursed",
    drug: "AVANT.TraitDrug",
    elixir: "AVANT.TraitElixir",
    emotion: "AVANT.TraitEmotion",
    expandable: "AVANT.TraitExpandable",
    fear: "AVANT.TraitFear",
    fey: "AVANT.TraitFey",
    fortune: "AVANT.TraitFortune",
    fulu: "AVANT.TraitFulu",
    gadget: "AVANT.TraitGadget",
    healing: "AVANT.TraitHealing",
    incapacitation: "AVANT.TraitIncapacitation",
    infused: "AVANT.TraitInfused",
    ingested: "AVANT.TraitIngested",
    inhaled: "AVANT.TraitInhaled",
    injury: "AVANT.TraitInjury",
    kobold: "AVANT.TraitKobold",
    light: "AVANT.TraitLight",
    linguistic: "AVANT.TraitLinguistic",
    lozenge: "AVANT.TraitLozenge",
    magical: "AVANT.TraitMagical",
    mechanical: "AVANT.TraitMechanical",
    misfortune: "AVANT.TraitMisfortune",
    missive: "AVANT.TraitMissive",
    morph: "AVANT.TraitMorph",
    mutagen: "AVANT.TraitMutagen",
    oil: "AVANT.TraitOil",
    olfactory: "AVANT.TraitOlfactory",
    poison: "AVANT.TraitPoison",
    polymorph: "AVANT.TraitPolymorph",
    possession: "AVANT.TraitPossession",
    potion: "AVANT.TraitPotion",
    precious: "AVANT.TraitPrecious",
    processed: "AVANT.TraitProcessed",
    scroll: "AVANT.TraitScroll",
    scrying: "AVANT.TraitScrying",
    spirit: "AVANT.TraitSpirit",
    sleep: "AVANT.TraitSleep",
    snare: "AVANT.TraitSnare",
    spellgun: "AVANT.TraitSpellgun",
    splash: "AVANT.TraitSplash",
    structure: "AVANT.TraitStructure",
    talisman: "AVANT.TraitTalisman",
    tea: "AVANT.TraitTea",
    teleportation: "AVANT.TraitTeleportation",
    trap: "AVANT.TraitTrap",
    virulent: "AVANT.TraitVirulent",
    visual: "AVANT.TraitVisual",
    wand: "AVANT.TraitWand",
};

const weaponActionTraits = R.pick(weaponTraits, [
    "agile",
    "propulsive",
    "backswing",
    "forceful",
    "reach",
    "sweep",
    "thrown",
    "volley-20",
    "volley-30",
    "volley-50",
    "volley-60",
]);

const actionTraits = {
    ...featTraits,
    ...consumableTraits,
    ...spellTraits,
    ...weaponActionTraits,
    "certain-kill": "AVANT.TraitCertainKill",
    summon: "AVANT.TraitSummon",
};

const effectTraits = R.omit(actionTraits, [
    ...R.keys(ancestryTraits),
    ...R.keys(classTraits),
    ...R.keys(weaponActionTraits),
    "additive",
    "additive1",
    "additive2",
    "additive3",
    "aftermath",
    "amp",
    "archetype",
    "attack",
    "backswing",
    "beast",
    "bottled-breath",
    "cantrip",
    "catalyst",
    "circus",
    "class",
    "clockwork",
    "coagulant",
    "composite",
    "composition",
    "concentrate",
    "consumable",
    "dedication",
    "deviant",
    "eidolon",
    "elixir",
    "esoterica",
    "expandable",
    "exploration",
    "finisher",
    "flourish",
    "focus",
    "forceful",
    "fulu",
    "gadget",
    "general",
    "infused",
    "lineage",
    "litany",
    "lozenge",
    "manipulate",
    "missive",
    "modification",
    "multiclass",
    "mutagen",
    "oath",
    "oil",
    "overflow",
    "pervasive-magic",
    "potion",
    "precious",
    "press",
    "processed",
    "propulsive",
    "reckless",
    "reincarnated",
    "revelation",
    "sanctified",
    "scroll",
    "secret",
    "skill",
    "snare",
    "spellgun",
    "splash",
    "structure",
    "subtle",
    "talisman",
    "tandem",
    "tea",
    "trap",
    "unstable",
    "vigilante",
    "wand",
] as const);

const hazardTraits = {
    ...creatureTraits,
    ...damageTraits,
    ...magicTraditions,
    alchemical: "AVANT.TraitAlchemical",
    auditory: "AVANT.TraitAuditory",
    consumable: "AVANT.TraitConsumable",
    curse: "AVANT.TraitCurse",
    environmental: "AVANT.TraitEnvironmental",
    haunt: "AVANT.TraitHaunt",
    inhaled: "AVANT.TraitInhaled",
    kaiju: "AVANT.TraitKaiju",
    mechanical: "AVANT.TraitMechanical",
    poison: "AVANT.TraitPoison",
    polymorph: "AVANT.TraitPolymorph",
    snare: "AVANT.TraitSnare",
    steam: "AVANT.TraitSteam",
    technological: "AVANT.TraitTechnological",
    teleportation: "AVANT.TraitTeleportation",
    trap: "AVANT.TraitTrap",
    virulent: "AVANT.TraitVirulent",
    visual: "AVANT.TraitVisual",
};

const vehicleTraits = {
    artifact: "AVANT.TraitArtifact",
    clockwork: "AVANT.TraitClockwork",
    magical: "AVANT.TraitMagical",
    teleportation: "AVANT.TraitTeleportation",
};

const equipmentTraits = {
    ...ancestryTraits,
    ...elementTraits,
    ...energyDamageTypes,
    ...magicTraditions,
    ...sanctificationTraits,
    additive: "AVANT.TraitAdditive",
    additive0: "AVANT.TraitAdditive0",
    additive1: "AVANT.TraitAdditive1",
    adjusted: "AVANT.TraitAdjusted",
    adjustment: "AVANT.TraitAdjustment",
    alchemical: "AVANT.TraitAlchemical",
    apex: "AVANT.TraitApex",
    artifact: "AVANT.TraitArtifact",
    auditory: "AVANT.TraitAuditory",
    aura: "AVANT.TraitAura",
    barding: "AVANT.TraitBarding",
    censer: "AVANT.TraitCenser",
    clockwork: "AVANT.TraitClockwork",
    coagulant: "AVANT.TraitCoagulant",
    coda: "AVANT.TraitCoda",
    companion: "AVANT.TraitCompanion",
    contract: "AVANT.TraitContract",
    consecration: "AVANT.TraitConsecration",
    cursed: "AVANT.TraitCursed",
    darkness: "AVANT.TraitDarkness",
    death: "AVANT.TraitDeath",
    detection: "AVANT.TraitDetection",
    eidolon: "AVANT.TraitEidolon",
    emotion: "AVANT.TraitEmotion",
    expandable: "AVANT.TraitExpandable",
    extradimensional: "AVANT.TraitExtradimensional",
    fear: "AVANT.TraitFear",
    figurehead: "AVANT.TraitFigurehead",
    focused: "AVANT.TraitFocused",
    fortune: "AVANT.TraitFortune",
    fulu: "AVANT.TraitFulu",
    gadget: "AVANT.TraitGadget",
    graft: "AVANT.TraitGraft",
    grimoire: "AVANT.TraitGrimoire",
    "harrow-court": "AVANT.TraitHarrowCourt",
    healing: "AVANT.TraitHealing",
    illusion: "AVANT.TraitIllusion",
    incapacitation: "AVANT.TraitIncapacitation",
    incorporeal: "AVANT.TraitIncorporeal",
    infused: "AVANT.TraitInfused",
    intelligent: "AVANT.TraitIntelligent",
    invested: "AVANT.TraitInvested",
    light: "AVANT.TraitLight",
    magical: "AVANT.TraitMagical",
    mechanical: "AVANT.TraitMechanical",
    mental: "AVANT.TraitMental",
    misfortune: "AVANT.TraitMisfortune",
    morph: "AVANT.TraitMorph",
    mounted: "AVANT.TraitMounted",
    mythic: "AVANT.TraitMythic",
    nonlethal: "AVANT.TraitNonlethal",
    plant: "AVANT.TraitPlant",
    poison: "AVANT.TraitPoison",
    polymorph: "AVANT.TraitPolymorph",
    portable: "AVANT.TraitPortable",
    precious: "AVANT.TraitPrecious",
    prediction: "AVANT.TraitPrediction",
    relic: "AVANT.TraitRelic",
    revelation: "AVANT.TraitRevelation",
    saggorak: "AVANT.TraitSaggorak",
    scrying: "AVANT.TraitScrying",
    shadow: "AVANT.TraitShadow",
    sleep: "AVANT.TraitSleep",
    spellgun: "AVANT.TraitSpellgun",
    spellheart: "AVANT.TraitSpellheart",
    spirit: "AVANT.TraitSpirit",
    staff: "AVANT.TraitStaff",
    steam: "AVANT.TraitSteam",
    structure: "AVANT.TraitStructure",
    tattoo: "AVANT.TraitTattoo",
    teleportation: "AVANT.TraitTeleportation",
    visual: "AVANT.TraitVisual",
    wand: "AVANT.TraitWand",
};

const shieldTraits = {
    ...sanctificationTraits,
    ...damageTraits,
    ...magicTraditions,
    apex: "AVANT.TraitApex",
    "deflecting-bludgeoning": "AVANT.TraitDeflectingBludgeoning",
    "deflecting-physical-ranged": "AVANT.TraitDeflectingPhysicalRanged",
    "deflecting-piercing": "AVANT.TraitDeflectingPiercing",
    "deflecting-slashing": "AVANT.TraitDeflectingSlashing",
    foldaway: "AVANT.TraitFoldaway",
    harnessed: "AVANT.TraitHarnessed",
    "hefty-2": "AVANT.TraitHefty2",
    inscribed: "AVANT.TraitInscribed",
    "integrated-1d6-b": "AVANT.TraitIntegrated1d6B",
    "integrated-1d6-p": "AVANT.TraitIntegrated1d6P",
    "integrated-1d6-s": "AVANT.TraitIntegrated1d6S",
    "integrated-1d6-s-versatile-p": "AVANT.TraitIntegrated1d6SVersatileP",
    invested: "AVANT.TraitInvested",
    "launching-dart": "AVANT.TraitLaunching",
    magical: "AVANT.TraitMagical",
    relic: "AVANT.TraitRelic",
    "shield-throw-20": "AVANT.TraitShieldThrow20",
    "shield-throw-30": "AVANT.TraitShieldThrow30",
};

const armorTraits = {
    ...sanctificationTraits,
    ...damageTraits,
    ...magicTraditions,
    adjusted: "AVANT.TraitAdjusted",
    alchemical: "AVANT.TraitAlchemical",
    apex: "AVANT.TraitApex",
    aquadynamic: "AVANT.TraitAquadynamic",
    artifact: "AVANT.TraitArtifact",
    auditory: "AVANT.TraitAuditory",
    aura: "AVANT.TraitAura",
    barding: "AVANT.TraitBarding",
    bulwark: "AVANT.TraitBulwark",
    clockwork: "AVANT.TraitClockwork",
    comfort: "AVANT.TraitComfort",
    companion: "AVANT.TraitCompanion",
    cursed: "AVANT.TraitCursed",
    "entrench-melee": "AVANT.TraitEntrenchMelee",
    "entrench-ranged": "AVANT.TraitEntrenchRanged",
    extradimensional: "AVANT.TraitExtradimensional",
    focused: "AVANT.TraitFocused",
    force: "AVANT.TraitForce",
    flexible: "AVANT.TraitFlexible",
    healing: "AVANT.TraitHealing",
    hindering: "AVANT.TraitHindering",
    illusion: "AVANT.TraitIllusion",
    inscribed: "AVANT.TraitInscribed",
    intelligent: "AVANT.TraitIntelligent",
    invested: "AVANT.TraitInvested",
    laminar: "AVANT.TraitLaminar",
    light: "AVANT.TraitLight",
    magical: "AVANT.TraitMagical",
    mythic: "AVANT.TraitMythic",
    noisy: "AVANT.TraitNoisy",
    plant: "AVANT.TraitPlant",
    ponderous: "AVANT.TraitPonderous",
    relic: "AVANT.TraitRelic",
};

const rangeDescriptions = R.mapToObj(RANGE_TRAITS, (trait) => [trait, "AVANT.TraitDescriptionRange"]);

const kingmakerTraits = {
    ...actionTraits,
    army: "AVANT.Kingmaker.Trait.army",
    cavalry: "AVANT.Kingmaker.Trait.cavalry",
    civic: "AVANT.Kingmaker.Trait.civic",
    commerce: "AVANT.Kingmaker.Trait.commerce",
    infantry: "AVANT.Kingmaker.Trait.infantry",
    kingdom: "AVANT.Kingmaker.Trait.kingdom",
    leadership: "AVANT.Kingmaker.Trait.leadership",
    maneuver: "AVANT.Kingmaker.Trait.maneuver",
    morale: "AVANT.Kingmaker.Trait.morale",
    region: "AVANT.Kingmaker.Trait.region",
    siege: "AVANT.Kingmaker.Trait.siege",
    skirmisher: "AVANT.Kingmaker.Trait.skirmisher",
    upkeep: "AVANT.Kingmaker.Trait.upkeep",
};

const kingmakerDescriptions = {
    cavalry: "AVANT.Kingmaker.TraitDescription.cavalry",
    infantry: "AVANT.Kingmaker.TraitDescription.infantry",
    siege: "AVANT.Kingmaker.TraitDescription.siege",
    skirmisher: "AVANT.Kingmaker.TraitDescription.skirmisher",
};

const preciousMaterialDescriptions = {
    abysium: "AVANT.PreciousMaterialAbysiumDescription",
    adamantine: "AVANT.PreciousMaterialAdamantineDescription",
    "cold-iron": "AVANT.PreciousMaterialColdIronDescription",
    duskwood: "AVANT.PreciousMaterialDuskwoodDescription",
    djezet: "AVANT.PreciousMaterialDjezetDescription",
    dragonhide: "AVANT.PreciousMaterialDragonhideDescription",
    dreamweb: "AVANT.PreciousMaterialDreamwebDescription",
    "grisantian-pelt": "AVANT.PreciousMaterialGrisantianPeltDescription",
    inubrix: "AVANT.PreciousMaterialInubrixDescription",
    dawnsilver: "AVANT.PreciousMaterialDawnsilverDescription",
    noqual: "AVANT.PreciousMaterialNoqualDescription",
    orichalcum: "AVANT.PreciousMaterialOrichalcumDescription",
    siccatite: "AVANT.PreciousMaterialSiccatiteDescription",
    silver: "AVANT.PreciousMaterialSilverDescription",
    sisterstone: "AVANT.PreciousMaterialSisterstoneDescription",
    "sisterstone-dusk": "AVANT.PreciousMaterialSisterstoneDescription",
    "sisterstone-scarlet": "AVANT.PreciousMaterialSisterstoneDescription",
    sloughstone: "AVANT.PreciousMaterialSloughstoneDescription",
    "sovereign-steel": "AVANT.PreciousMaterialSovereignSteelDescription",
    warpglass: "AVANT.PreciousMaterialWarpglassDescription",
};

const traitDescriptions = {
    ...kingmakerDescriptions,
    aasimar: "AVANT.TraitDescriptionAasimar",
    aberration: "AVANT.TraitDescriptionAberration",
    abjuration: "AVANT.TraitDescriptionAbjuration",
    acid: "AVANT.TraitDescriptionAcid",
    additive: "AVANT.TraitDescriptionAdditive",
    additive0: "AVANT.TraitDescriptionAdditive",
    additive1: "AVANT.TraitDescriptionAdditive",
    additive2: "AVANT.TraitDescriptionAdditive",
    additive3: "AVANT.TraitDescriptionAdditive",
    adjusted: "AVANT.TraitDescriptionAdjusted",
    adjustment: "AVANT.TraitDescriptionAdjustment",
    aeon: "AVANT.TraitDescriptionAeon",
    aesir: "AVANT.TraitDescriptionAesir",
    aftermath: "AVANT.TraitDescriptionAftermath",
    agathion: "AVANT.TraitDescriptionAgathion",
    agile: "AVANT.TraitDescriptionAgile",
    air: "AVANT.TraitDescriptionAir",
    aiuvarin: "AVANT.TraitDescriptionAiuvarin",
    alchemical: "AVANT.TraitDescriptionAlchemical",
    alchemist: "AVANT.TraitDescriptionAlchemist",
    amphibious: "AVANT.TraitDescriptionAmphibious",
    anadi: "AVANT.TraitDescriptionAnadi",
    android: "AVANT.TraitDescriptionAndroid",
    angel: "AVANT.TraitDescriptionAngel",
    animal: "AVANT.TraitDescriptionAnimal",
    animist: "AVANT.TraitDescriptionAnimist",
    apex: "AVANT.TraitDescriptionApex",
    aphorite: "AVANT.TraitDescriptionAphorite",
    apparition: "AVANT.TraitDescriptionApparition",
    aquadynamic: "AVANT.TraitDescriptionAquadynamic",
    aquatic: "AVANT.TraitDescriptionAquatic",
    arcane: "AVANT.TraitDescriptionArcane",
    archetype: "AVANT.TraitDescriptionArchetype",
    archon: "AVANT.TraitDescriptionArchon",
    ardande: "AVANT.TraitDescriptionArdande",
    astral: "AVANT.TraitDescriptionAstral",
    artifact: "AVANT.TraitDescriptionArtifact",
    athamaru: "AVANT.TraitDescriptionAthamaru",
    attached: "AVANT.TraitDescriptionAttached",
    "attached-to-crossbow-or-firearm": "AVANT.TraitDescriptionAttached",
    "attached-to-shield": "AVANT.TraitDescriptionAttached",
    attack: "AVANT.TraitDescriptionAttack",
    auditory: "AVANT.TraitDescriptionAuditory",
    aura: "AVANT.TraitDescriptionAura",
    automaton: "AVANT.TraitDescriptionAutomaton",
    "awakened-animal": "AVANT.TraitDescriptionAwakenedAnimal",
    azarketi: "AVANT.TraitDescriptionAzarketi",
    azata: "AVANT.TraitDescriptionAzata",
    backstabber: "AVANT.TraitDescriptionBackstabber",
    backswing: "AVANT.TraitDescriptionBackswing",
    barbarian: "AVANT.TraitDescriptionBarbarian",
    bard: "AVANT.TraitDescriptionBard",
    beast: "AVANT.TraitDescriptionBeast",
    beastkin: "AVANT.TraitDescriptionBeastkin",
    blight: "AVANT.TraitDescriptionBlight",
    boggard: "AVANT.TraitDescriptionBoggard",
    bomb: "AVANT.TraitDescriptionBomb",
    "bottled-breath": "AVANT.TraitDescriptionBottledBreath",
    brace: "AVANT.TraitDescriptionBrace",
    brutal: "AVANT.TraitDescriptionBrutal",
    bugbear: "AVANT.TraitDescriptionBugbear",
    bulwark: "AVANT.TraitDescriptionBulwark",
    caligni: "AVANT.TraitDescriptionCaligni",
    calling: "AVANT.TraitDescriptionCalling",
    cantrip: "AVANT.TraitDescriptionCantrip",
    "capacity-2": "AVANT.TraitDescriptionCapacity",
    "capacity-3": "AVANT.TraitDescriptionCapacity",
    "capacity-4": "AVANT.TraitDescriptionCapacity",
    "capacity-5": "AVANT.TraitDescriptionCapacity",
    catalyst: "AVANT.TraitDescriptionCatalyst",
    celestial: "AVANT.TraitDescriptionCelestial",
    catfolk: "AVANT.TraitDescriptionCatfolk",
    censer: "AVANT.TraitDescriptionCenser",
    centaur: "AVANT.TraitDescriptionCentaur",
    "certain-kill": "AVANT.TraitDescriptionCertainKill",
    champion: "AVANT.TraitDescriptionChampion",
    changeling: "AVANT.TraitDescriptionChangeling",
    class: "AVANT.TraitDescriptionClass",
    cleric: "AVANT.TraitDescriptionCleric",
    climbing: "AVANT.TraitDescriptionClimbing",
    clockwork: "AVANT.TraitDescriptionClockwork",
    coatl: "AVANT.TraitDescriptionCoatl",
    cobbled: "AVANT.TraitDescriptionCobbled",
    coagulant: "AVANT.TraitDescriptionCoagulant",
    coda: "AVANT.TraitDescriptionCoda",
    cold: "AVANT.TraitDescriptionCold",
    combination: "AVANT.TraitDescriptionCombination",
    comfort: "AVANT.TraitDescriptionComfort",
    common: "AVANT.TraitDescriptionCommon",
    companion: "AVANT.TraitDescriptionCompanion",
    complex: "AVANT.TraitDescriptionComplex",
    composite: "AVANT.TraitDescriptionComposite",
    composition: "AVANT.TraitDescriptionComposition",
    concealable: "AVANT.TraitDescriptionConcealable",
    concentrate: "AVANT.TraitDescriptionConcentrate",
    concussive: "AVANT.TraitDescriptionConcussive",
    conrasu: "AVANT.TraitDescriptionConrasu",
    consecration: "AVANT.TraitDescriptionConsecration",
    construct: "AVANT.TraitDescriptionConstruct",
    consumable: "AVANT.TraitDescriptionConsumable",
    contact: "AVANT.TraitDescriptionContact",
    contingency: "AVANT.TraitDescriptionContingency",
    contract: "AVANT.TraitDescriptionContract",
    "critical-fusion": "AVANT.TraitDescriptionCriticalFusion",
    curse: "AVANT.TraitDescriptionCurse",
    cursebound: "AVANT.TraitDescriptionCursebound",
    cursed: "AVANT.TraitDescriptionCursed",
    daemon: "AVANT.TraitDescriptionDaemon",
    darkness: "AVANT.TraitDescriptionDarkness",
    darvakka: "AVANT.TraitDescriptionDarvakka",
    "deadly-2d10": "AVANT.TraitDescriptionDeadly",
    "deadly-2d12": "AVANT.TraitDescriptionDeadly",
    "deadly-2d8": "AVANT.TraitDescriptionDeadly",
    "deadly-3d10": "AVANT.TraitDescriptionDeadly",
    "deadly-3d12": "AVANT.TraitDescriptionDeadly",
    "deadly-3d8": "AVANT.TraitDescriptionDeadly",
    "deadly-4d10": "AVANT.TraitDescriptionDeadly",
    "deadly-4d12": "AVANT.TraitDescriptionDeadly",
    "deadly-4d8": "AVANT.TraitDescriptionDeadly",
    "deadly-d10": "AVANT.TraitDescriptionDeadly",
    "deadly-d12": "AVANT.TraitDescriptionDeadly",
    "deadly-d6": "AVANT.TraitDescriptionDeadly",
    "deadly-d8": "AVANT.TraitDescriptionDeadly",
    "deadly-d4": "AVANT.TraitDescriptionDeadly",
    death: "AVANT.TraitDescriptionDeath",
    "deflecting-bludgeoning": "AVANT.TraitDescriptionDeflecting",
    "deflecting-physical-ranged": "AVANT.TraitDescriptionDeflecting",
    "deflecting-slashing": "AVANT.TraitDescriptionDeflecting",
    dedication: "AVANT.TraitDescriptionDedication",
    demon: "AVANT.TraitDescriptionDemon",
    dero: "AVANT.TraitDescriptionDero",
    destiny: "AVANT.TraitDescriptionDestiny",
    detection: "AVANT.TraitDescriptionDetection",
    deviant: "AVANT.TraitDescriptionDeviant",
    devil: "AVANT.TraitDescriptionDevil",
    dhampir: "AVANT.TraitDescriptionDhampir",
    dinosaur: "AVANT.TraitDescriptionDinosaur",
    disarm: "AVANT.TraitDescriptionDisarm",
    disease: "AVANT.TraitDescriptionDisease",
    divination: "AVANT.TraitDescriptionDivination",
    divine: "AVANT.TraitDescriptionDivine",
    "double-barrel": "AVANT.TraitDescriptionDoubleBarrel",
    downtime: "AVANT.TraitDescriptionDowntime",
    dragon: "AVANT.TraitDescriptionDragon",
    dragonblood: "AVANT.TraitDescriptionDragonblood",
    dromaar: "AVANT.TraitDescriptionDromaar",
    drug: "AVANT.TraitDescriptionDrug",
    druid: "AVANT.TraitDescriptionDruid",
    duskwalker: "AVANT.TraitDescriptionDuskwalker",
    dwarf: "AVANT.TraitDescriptionDwarf",
    earth: "AVANT.TraitDescriptionEarth",
    eidolon: "AVANT.TraitDescriptionEidolon",
    electricity: "AVANT.TraitDescriptionElectricity",
    elemental: "AVANT.TraitDescriptionElemental",
    elf: "AVANT.TraitDescriptionElf",
    elixir: "AVANT.TraitDescriptionElixir",
    emotion: "AVANT.TraitDescriptionEmotion",
    "entrench-melee": "AVANT.TraitDescriptionEntrench",
    "entrench-ranged": "AVANT.TraitDescriptionEntrench",
    environment: "AVANT.TraitDescriptionEnvironment",
    esoterica: "AVANT.TraitDescriptionEsoterica",
    ethereal: "AVANT.TraitDescriptionEthereal",
    evolution: "AVANT.TraitDescriptionEvolution",
    exemplar: "AVANT.TraitDescriptionExemplar",
    expandable: "AVANT.TraitDescriptionExpandable",
    experiment: "AVANT.TraitDescriptionExperiment",
    exploration: "AVANT.TraitDescriptionExploration",
    extradimensional: "AVANT.TraitDescriptionExtradimensional",
    "fatal-aim-d10": "AVANT.TraitDescriptionFatalAim",
    "fatal-aim-d12": "AVANT.TraitDescriptionFatalAim",
    "fatal-d10": "AVANT.TraitDescriptionFatal",
    "fatal-d12": "AVANT.TraitDescriptionFatal",
    "fatal-d8": "AVANT.TraitDescriptionFatal",
    fear: "AVANT.TraitDescriptionFear",
    fetchling: "AVANT.TraitDescriptionFetchling",
    fey: "AVANT.TraitDescriptionFey",
    fiend: "AVANT.TraitDescriptionFiend",
    fighter: "AVANT.TraitDescriptionFighter",
    figurehead: "AVANT.TraitDescriptionFigurehead",
    finesse: "AVANT.TraitDescriptionFinesse",
    finisher: "AVANT.TraitDescriptionFinisher",
    fire: "AVANT.TraitDescriptionFire",
    fleshwarp: "AVANT.TraitDescriptionFleshwarp",
    flexible: "AVANT.TraitDescriptionFlexible",
    flourish: "AVANT.TraitDescriptionFlourish",
    focus: "AVANT.TraitDescriptionFocus",
    focused: "AVANT.TraitDescriptionFocused",
    foldaway: "AVANT.TraitDescriptionFoldaway",
    force: "AVANT.TraitDescriptionForce",
    forceful: "AVANT.TraitDescriptionForceful",
    fortune: "AVANT.TraitDescriptionFortune",
    "free-hand": "AVANT.TraitDescriptionFreeHand",
    fulu: "AVANT.TraitDescriptionFulu",
    fungus: "AVANT.TraitDescriptionFungus",
    gadget: "AVANT.TraitDescriptionGadget",
    ganzi: "AVANT.TraitDescriptionGanzi",
    graft: "AVANT.TraitDescriptionGraft",
    general: "AVANT.TraitDescriptionGeneral",
    genie: "AVANT.TraitDescriptionGenie",
    geniekin: "AVANT.TraitDescriptionGeniekin",
    ghoran: "AVANT.TraitDescriptionGhoran",
    ghost: "AVANT.TraitDescriptionGhost",
    ghoul: "AVANT.TraitDescriptionGhoul",
    ghul: "AVANT.TraitDescriptionGhul",
    giant: "AVANT.TraitDescriptionGiant",
    gnoll: "AVANT.TraitDescriptionGnoll",
    gnome: "AVANT.TraitDescriptionGnome",
    goblin: "AVANT.TraitDescriptionGoblin",
    goloma: "AVANT.TraitDescriptionGoloma",
    grapple: "AVANT.TraitDescriptionGrapple",
    gremlin: "AVANT.TraitDescriptionGremlin",
    grimoire: "AVANT.TraitDescriptionGrimoire",
    grippli: "AVANT.TraitDescriptionGrippli",
    gunslinger: "AVANT.TraitDescriptionGunslinger",
    hag: "AVANT.TraitDescriptionHag",
    halfling: "AVANT.TraitDescriptionHalfling",
    "jousting-d4": "AVANT.TraitDescriptionJousting",
    "jousting-d6": "AVANT.TraitDescriptionJousting",
    "jousting-d8": "AVANT.TraitDescriptionJousting",
    "jousting-d10": "AVANT.TraitDescriptionJousting",
    hampering: "AVANT.TraitDescriptionHampering",
    harnessed: "AVANT.TraitDescriptionHarnessed",
    haunt: "AVANT.TraitDescriptionHaunt",
    healing: "AVANT.TraitDescriptionHealing",
    "hefty-14": "AVANT.TraitDescriptionHefty",
    hex: "AVANT.TraitDescriptionHex",
    hindering: "AVANT.TraitDescriptionHindering",
    hobgoblin: "AVANT.TraitDescriptionHobgoblin",
    holy: "AVANT.TraitDescriptionHoly",
    hryngar: "AVANT.TraitDescriptionHryngar",
    human: "AVANT.TraitDescriptionHuman",
    humanoid: "AVANT.TraitDescriptionHumanoid",
    naari: "AVANT.TraitDescriptionNaari",
    ikon: "AVANT.TraitDescriptionIkon",
    illusion: "AVANT.TraitDescriptionIllusion",
    impulse: "AVANT.TraitDescriptionImpulse",
    incapacitation: "AVANT.TraitDescriptionIncapacitation",
    incarnate: "AVANT.TraitDescriptionIncarnate",
    incorporeal: "AVANT.TraitDescriptionIncorporeal",
    infused: "AVANT.TraitDescriptionInfused",
    infusion: "AVANT.TraitDescriptionInfusion",
    ingested: "AVANT.TraitDescriptionIngested",
    inhaled: "AVANT.TraitDescriptionInhaled",
    injection: "AVANT.TraitDescriptionInjection",
    injury: "AVANT.TraitDescriptionInjury",
    inscribed: "AVANT.TraitDescriptionInscribed",
    "integrated-1d6-b": "AVANT.TraitDescriptionIntegrated",
    "integrated-1d6-p": "AVANT.TraitDescriptionIntegrated",
    "integrated-1d6-s": "AVANT.TraitDescriptionIntegrated",
    "integrated-1d6-s-versatile-p": "AVANT.TraitDescriptionIntegrated",
    intelligent: "AVANT.TraitDescriptionIntelligent",
    inventor: "AVANT.TraitDescriptionInventor",
    invested: "AVANT.TraitDescriptionInvested",
    investigator: "AVANT.TraitDescriptionInvestigator",
    kashrishi: "AVANT.TraitDescriptionKashrishi",
    "keep-stone": "AVANT.PreciousMaterialKeepStoneDescription",
    kholo: "AVANT.TraitDescriptionKholo",
    kickback: "AVANT.TraitDescriptionKickback",
    kineticist: "AVANT.TraitDescriptionKineticist",
    kitsune: "AVANT.TraitDescriptionKitsune",
    kobold: "AVANT.TraitDescriptionKobold",
    laminar: "AVANT.TraitDescriptionLaminar",
    "launching-dart": "AVANT.TraitDescriptionLaunching",
    leshy: "AVANT.TraitDescriptionLeshy",
    light: "AVANT.TraitDescriptionLight",
    linguistic: "AVANT.TraitDescriptionLinguistic",
    litany: "AVANT.TraitDescriptionLitany",
    lizardfolk: "AVANT.TraitDescriptionLizardfolk",
    lozenge: "AVANT.TraitDescriptionLozenge",
    magical: "AVANT.TraitDescriptionMagical",
    magus: "AVANT.TraitDescriptionMagus",
    manipulate: "AVANT.TraitDescriptionManipulate",
    mechanical: "AVANT.TraitDescriptionMechanical",
    mental: "AVANT.TraitDescriptionMental",
    merfolk: "AVANT.TraitDescriptionMerfolk",
    metal: "AVANT.TraitDescriptionMetal",
    mindless: "AVANT.TraitDescriptionMindless",
    mindshift: "AVANT.TraitDescriptionMindshift",
    minion: "AVANT.TraitDescriptionMinion",
    minotaur: "AVANT.TraitDescriptionMinotaur",
    misfortune: "AVANT.TraitDescriptionMisfortune",
    missive: "AVANT.TraitDescriptionMissive",
    modification: "AVANT.TraitDescriptionModification",
    modular: "AVANT.TraitDescriptionModular",
    monitor: "AVANT.TraitDescriptionMonitor",
    monk: "AVANT.TraitDescriptionMonk",
    morph: "AVANT.TraitDescriptionMorph",
    mounted: "AVANT.TraitDescriptionMounted",
    move: "AVANT.TraitDescriptionMove",
    multiclass: "AVANT.TraitDescriptionMulticlass",
    mummy: "AVANT.TraitDescriptionMummy",
    mutagen: "AVANT.TraitDescriptionMutagen",
    mutant: "AVANT.TraitDescriptionMutant",
    mythic: "AVANT.TraitDescriptionMythic",
    nagaji: "AVANT.TraitDescriptionNagaji",
    nephilim: "AVANT.TraitDescriptionNephilim",
    nindoru: "AVANT.TraitDescriptionNindoru",
    noisy: "AVANT.TraitDescriptionNoisy",
    nonlethal: "AVANT.TraitDescriptionNonlethal",
    nymph: "AVANT.TraitDescriptionNymph",
    oath: "AVANT.TraitDescriptionOath",
    occult: "AVANT.TraitDescriptionOccult",
    oil: "AVANT.TraitDescriptionOil",
    olfactory: "AVANT.TraitDescriptionOlfactory",
    oni: "AVANT.TraitDescriptionOni",
    ooze: "AVANT.TraitDescriptionOoze",
    oracle: "AVANT.TraitDescriptionOracle",
    orc: "AVANT.TraitDescriptionOrc",
    oread: "AVANT.TraitDescriptionOread",
    overflow: "AVANT.TraitDescriptionOverflow",
    palinthanos: "AVANT.TraitDescriptionPalinthanos",
    parry: "AVANT.TraitDescriptionParry",
    peachwood: "AVANT.PreciousMaterialPeachwoodDescription",
    "persona-flirt": "AVANT.TraitPersonaFlirtDescription",
    "persona-guardian": "AVANT.TraitPersonaGuardianDescription",
    "persona-leader": "AVANT.TraitPersonaLeaderDescription",
    "persona-scholar": "AVANT.TraitPersonaScholarDescription",
    "persona-scoundrel": "AVANT.TraitPersonaScoundrelDescription",
    "persona-underdog": "AVANT.TraitPersonaUnderdogDescription",
    "persona-warrior": "AVANT.TraitPersonaWarriorDescription",
    "persona-wildcard": "AVANT.TraitPersonaWildcardDescription",
    phantom: "AVANT.TraitDescriptionPhantom",
    plant: "AVANT.TraitDescriptionPlant",
    poison: "AVANT.TraitDescriptionPoison",
    polymorph: "AVANT.TraitDescriptionPolymorph",
    ponderous: "AVANT.TraitDescriptionPonderous",
    poppet: "AVANT.TraitDescriptionPoppet",
    portable: "AVANT.TraitDescriptionPortable",
    possession: "AVANT.TraitDescriptionPossession",
    potion: "AVANT.TraitDescriptionPotion",
    precious: "AVANT.TraitDescriptionPrecious",
    prediction: "AVANT.TraitDescriptionPrediction",
    processed: "AVANT.TraitDescriptionProcessed",
    press: "AVANT.TraitDescriptionPress",
    primal: "AVANT.TraitDescriptionPrimal",
    propulsive: "AVANT.TraitDescriptionPropulsive",
    protean: "AVANT.TraitDescriptionProtean",
    psyche: "AVANT.TraitDescriptionPsyche",
    psychic: "AVANT.TraitDescriptionPsychic",
    psychopomp: "AVANT.TraitDescriptionPsychopomp",
    qlippoth: "AVANT.TraitDescriptionQlippoth",
    radiation: "AVANT.TraitDescriptionRadiation",
    rage: "AVANT.TraitDescriptionRage",
    akshasa: "AVANT.TraitDescriptionRakshasa",
    ranger: "AVANT.TraitDescriptionRanger",
    ...rangeDescriptions,
    "ranged-trip": "AVANT.TraitDescriptionRangedTrip",
    rare: "AVANT.TraitDescriptionRare",
    ratfolk: "AVANT.TraitDescriptionRatfolk",
    razing: "AVANT.TraitDescriptionRazing",
    reach: "AVANT.TraitDescriptionReach",
    "reach-0": "AVANT.TraitDescriptionReach",
    "reach-10": "AVANT.TraitDescriptionReach",
    "reach-100": "AVANT.TraitDescriptionReach",
    "reach-120": "AVANT.TraitDescriptionReach",
    "reach-1000": "AVANT.TraitDescriptionReach",
    "reach-15": "AVANT.TraitDescriptionReach",
    "reach-20": "AVANT.TraitDescriptionReach",
    "reach-200": "AVANT.TraitDescriptionReach",
    "reach-25": "AVANT.TraitDescriptionReach",
    "reach-30": "AVANT.TraitDescriptionReach",
    "reach-40": "AVANT.TraitDescriptionReach",
    "reach-50": "AVANT.TraitDescriptionReach",
    "reach-60": "AVANT.TraitDescriptionReach",
    recovery: "AVANT.TraitDescriptionRecovery",
    reincarnated: "AVANT.TraitDescriptionReincarnated",
    reflection: "AVANT.TraitDescriptionReflection",
    relic: "AVANT.TraitDescriptionRelic",
    reload: "AVANT.TraitDescriptionReload",
    "reload-0": "AVANT.TraitDescriptionReload",
    "reload-1": "AVANT.TraitDescriptionReload",
    "reload-1-min": "AVANT.TraitDescriptionReload",
    "reload-2": "AVANT.TraitDescriptionReload",
    repeating: "AVANT.TraitDescriptionRepeating",
    resonant: "AVANT.TraitDescriptionResonant",
    revelation: "AVANT.TraitDescriptionRevelation",
    rogue: "AVANT.TraitDescriptionRogue",
    saggorak: "AVANT.TraitDescriptionSaggorak",
    sanctified: "AVANT.TraitDescriptionSanctified",
    "scatter-10": "AVANT.TraitDescriptionScatter",
    "scatter-15": "AVANT.TraitDescriptionScatter",
    "scatter-20": "AVANT.TraitDescriptionScatter",
    "scatter-5": "AVANT.TraitDescriptionScatter",
    scroll: "AVANT.TraitDescriptionScroll",
    scrying: "AVANT.TraitDescriptionScrying",
    secret: "AVANT.TraitDescriptionSecret",
    sedacthy: "AVANT.TraitDescriptionSedacthy",
    serpentfolk: "AVANT.TraitDescriptionSerpentfolk",
    shadow: "AVANT.TraitDescriptionShadow",
    "shield-throw-20": "AVANT.TraitDescriptionShieldThrow",
    "shield-throw-30": "AVANT.TraitDescriptionShieldThrow",
    shisk: "AVANT.TraitDescriptionShisk",
    shoony: "AVANT.TraitDescriptionShoony",
    shove: "AVANT.TraitDescriptionShove",
    skeleton: "AVANT.TraitDescriptionSkeleton",
    skill: "AVANT.TraitDescriptionSkill",
    sleep: "AVANT.TraitDescriptionSleep",
    snare: "AVANT.TraitDescriptionSnare",
    social: "AVANT.TraitDescriptionSocial",
    sonic: "AVANT.TraitDescriptionSonic",
    sorcerer: "AVANT.TraitDescriptionSorcerer",
    soulbound: "AVANT.TraitDescriptionSoulbound",
    spellgun: "AVANT.TraitDescriptionSpellgun",
    spellheart: "AVANT.TraitDescriptionSpellheart",
    spellshape: "AVANT.TraitDescriptionSpellshape",
    spellshot: "AVANT.TraitNoDescription",
    spirit: "AVANT.TraitDescriptionSpirit",
    splash: "AVANT.TraitDescriptionSplash",
    "splash-10": "AVANT.TraitDescriptionSplash10",
    sprite: "AVANT.TraitDescriptionSprite",
    staff: "AVANT.TraitDescriptionStaff",
    stance: "AVANT.TraitDescriptionStance",
    steam: "AVANT.TraitDescriptionSteam",
    strix: "AVANT.TraitDescriptionStrix",
    structure: "AVANT.TraitDescriptionStructure",
    subtle: "AVANT.TraitDescriptionSubtle",
    suli: "AVANT.TraitDescriptionSuli",
    summon: "AVANT.TraitDescriptionSummon",
    summoned: "AVANT.TraitDescriptionSummoned",
    summoner: "AVANT.TraitDescriptionSummoner",
    surki: "AVANT.TraitDescriptionSurki",
    swashbuckler: "AVANT.TraitDescriptionSwashbuckler",
    swarm: "AVANT.TraitDescriptionSwarm",
    sweep: "AVANT.TraitDescriptionSweep",
    sylph: "AVANT.TraitDescriptionSylph",
    talisman: "AVANT.TraitDescriptionTalisman",
    talos: "AVANT.TraitDescriptionTalos",
    tandem: "AVANT.TraitDescriptionTandem",
    tane: "AVANT.TraitDescriptionTane",
    tattoo: "AVANT.TraitDescriptionTattoo",
    tea: "AVANT.TraitDescriptionTea",
    tearing: "AVANT.TraitDescriptionTearing",
    tech: "AVANT.TraitDescriptionTech",
    telepathy: "AVANT.TraitDescriptionTelepathy",
    teleportation: "AVANT.TraitDescriptionTeleportation",
    tengu: "AVANT.TraitDescriptionTengu",
    tethered: "AVANT.TraitDescriptionTethered",
    thaumaturge: "AVANT.TraitDescriptionThaumaturge",
    thrown: "AVANT.TraitDescriptionThrown",
    "thrown-10": "AVANT.TraitDescriptionThrown",
    "thrown-100": "AVANT.TraitDescriptionThrown",
    "thrown-15": "AVANT.TraitDescriptionThrown",
    "thrown-20": "AVANT.TraitDescriptionThrown",
    "thrown-200": "AVANT.TraitDescriptionThrown",
    "thrown-25": "AVANT.TraitDescriptionThrown",
    "thrown-30": "AVANT.TraitDescriptionThrown",
    "thrown-40": "AVANT.TraitDescriptionThrown",
    "thrown-50": "AVANT.TraitDescriptionThrown",
    "thrown-60": "AVANT.TraitDescriptionThrown",
    "thrown-80": "AVANT.TraitDescriptionThrown",
    tiefling: "AVANT.TraitDescriptionTiefling",
    time: "AVANT.TraitDescriptionTime",
    training: "AVANT.TraitDescriptionTraining",
    transcendence: "AVANT.TraitDescriptionTranscendence",
    trap: "AVANT.TraitDescriptionTrap",
    trip: "AVANT.TraitDescriptionTrip",
    troll: "AVANT.TraitDescriptionTroll",
    "true-name": "AVANT.TraitDescriptionTrueName",
    twin: "AVANT.TraitDescriptionTwin",
    "two-hand-d10": "AVANT.TraitDescriptionTwoHand",
    "two-hand-d12": "AVANT.TraitDescriptionTwoHand",
    "two-hand-d6": "AVANT.TraitDescriptionTwoHand",
    "two-hand-d8": "AVANT.TraitDescriptionTwoHand",
    unarmed: "AVANT.TraitDescriptionUnarmed",
    uncommon: "AVANT.TraitDescriptionUncommon",
    undine: "AVANT.TraitDescriptionUndine",
    undead: "AVANT.TraitDescriptionUndead",
    unholy: "AVANT.TraitDescriptionUnholy",
    unique: "AVANT.TraitDescriptionUnique",
    unstable: "AVANT.TraitDescriptionUnstable",
    vampire: "AVANT.TraitDescriptionVampire",
    vanara: "AVANT.TraitDescriptionVanara",
    vishkanya: "AVANT.TraitDescriptionVishkanya",
    vehicular: "AVANT.TraitDescriptionVehicular",
    venomous: "AVANT.TraitDescriptionVenomous",
    "versatile-acid": "AVANT.TraitDescriptionVersatile",
    "versatile-b": "AVANT.TraitDescriptionVersatile",
    "versatile-cold": "AVANT.TraitDescriptionVersatile",
    "versatile-electricity": "AVANT.TraitDescriptionVersatile",
    "versatile-fire": "AVANT.TraitDescriptionVersatile",
    "versatile-force": "AVANT.TraitDescriptionVersatile",
    "versatile-p": "AVANT.TraitDescriptionVersatile",
    "versatile-poison": "AVANT.TraitDescriptionVersatile",
    "versatile-s": "AVANT.TraitDescriptionVersatile",
    "versatile-sonic": "AVANT.TraitDescriptionVersatile",
    "versatile-spirit": "AVANT.TraitDescriptionVersatile",
    "versatile-vitality": "AVANT.TraitDescriptionVersatile",
    "versatile-void": "AVANT.TraitDescriptionVersatile",
    virulent: "AVANT.TraitDescriptionVirulent",
    visual: "AVANT.TraitDescriptionVisual",
    vitality: "AVANT.TraitDescriptionVitality",
    void: "AVANT.TraitDescriptionVoid",
    "volley-20": "AVANT.TraitDescriptionVolley",
    "volley-30": "AVANT.TraitDescriptionVolley",
    "volley-50": "AVANT.TraitDescriptionVolley",
    "volley-60": "AVANT.TraitDescriptionVolley",
    wand: "AVANT.TraitDescriptionWand",
    wandering: "AVANT.TraitDescriptionWandering",
    water: "AVANT.TraitDescriptionWater",
    werecreature: "AVANT.TraitDescriptionWerecreature",
    wight: "AVANT.TraitDescriptionWight",
    witch: "AVANT.TraitDescriptionWitch",
    wizard: "AVANT.TraitDescriptionWizard",
    wraith: "AVANT.TraitDescriptionWraith",
    wood: "AVANT.TraitDescriptionWood",
    xulgath: "AVANT.TraitDescriptionXulgath",
    zombie: "AVANT.TraitDescriptionZombie",
    ...preciousMaterialDescriptions,
};

export {
    actionTraits,
    ancestryTraits,
    armorTraits,
    backgroundTraits,
    classTraits,
    consumableTraits,
    creatureTraits,
    damageTraits,
    effectTraits,
    elementTraits,
    energyDamageTypes,
    equipmentTraits,
    featTraits,
    hazardTraits,
    kingmakerTraits,
    magicTraditions,
    npcAttackTraits,
    otherArmorTags,
    otherConsumableTags,
    otherWeaponTags,
    preciousMaterials,
    shieldTraits,
    spellTraits,
    traitDescriptions,
    vehicleTraits,
    weaponTraits,
    type ElementTrait,
};
